apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ .Values.flaskApp.image }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "90Mi"
            cpu: "50m"
          limits:
            memory: "130Mi"
            cpu: "100m"
        ports:
        - containerPort: {{ .Values.flaskApp.port }}
        env:
        # VARIABLES FROM K8S CONFIG MAP
        - name: FLASK_ENV
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.initSqlConfigMapName }}
              key: FLASK_ENV
        - name: MYSQL_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.initSqlConfigMapName }}
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.initSqlConfigMapName }}
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: {{ .Values.flaskApp.mysqlPasswordSecretKey }}
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.initSqlConfigMapName }}
              key: MYSQL_DATABASE
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.initSqlConfigMapName }}
              key: PORT
