apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: {{ .Values.mysql.rootPasswordSecretKey }}
        - name: MYSQL_DATABASE
          value: {{ .Values.flaskApp.mysqlDatabase }}
        - name: MYSQL_USER
          value: {{ .Values.flaskApp.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: {{ .Values.flaskApp.mysqlPasswordSecretKey }}
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: init-sql
        configMap:
          name: {{ .Values.initSqlConfigMapName }}
